XDOJ:
	# g++ main.cpp DataBase.cpp Judger.cpp Problem.cpp ProblemSet.cpp Control.cpp -I ../include -L ../lib -o app -ljsoncpp -pthread -std=c++11 -lmysqlclient -ljudger
	g++ *.cpp -I ../include -L ../lib -o app -ljsoncpp -pthread -std=c++11 -lmysqlclient -ljudger